# 全環境共通環境設定

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 8080
  servlet:
    # context-path: /app
    session:
      timeout: 2h
  tomcat:
    use-relative-redirects: true
    redirect-context-root: false
  forward-headers-strategy: NATIVE
# SPRING CONFIGURATION
spring:
  # MVC
  # MVC じゃないのでコメントアウト
  # mvc:
  #   hiddenmethod:
  #     filter:
  #       enabled: true

  # servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB
  # resources
  resources:
    chain:
      cache: true
      strategy:
        content:
          enabled: true
          paths: /**
      compressed: true
    cache:
      period: 86400
  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    enabled: true
    cache: true
  # SPRING SESSION
  session:
    store-type: REDIS
    timeout: 2h
    redis:
      flush-mode: ON_SAVE
      namespace: spring:session
  # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    driverClassName: r2dbc:h2:file:/data/sample
    sql-script-encoding: UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select 1
      connection-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 10
    # initialization-mode: always
  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  # JPA じゃないのでコメントアウト
  # jpa:
  #   database: POSTGRESQL
  #   # show-sql: true
  #   hibernate:
  #     ddl-auto: update
  #   properties:
  #     hibernate:
  #       session_factory:
  #         interceptor: com.aisarweb.common.fw.SqlLogger
  #       dialect: org.hibernate.dialect.PostgreSQLDialect
  #       jdbc:
  #         batch_size: 100

  # JACKSON CONFIGURATION
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      write-durations-as-timestamps: true
  # INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    basename: i18n/messages_ja, i18n/screen_item, i18n/system, i18n/screen_name
    encoding: utf-8

# ACTUATOR
management:
  endpoint:
    health:
      show-details: ALWAYS

# LOGGING CONFIGURATION
logging:
  level:
    org.springframework: warn
    org.springframework.web: warn
    org.springframework.security: warn
    # org.hibernate.SQL: debug
    # org.hibernate.type.descriptor.sql.BasicBinder: trace
    # org.hibernate.type.EnumType: trace
    com:aisarweb: debug
